#!/bin/bash
clear
start=`date +%s`
echo "script made by eoghan2t7 of xda"
printf "say thanks to him if this helped you :) \n\n"
wmctrl -r :ACTIVE: -N "Applying Build Settings"
NOW=$(date +"%d-%m-%Y")
echo "Current Date : $NOW"
echo "Applying Build Settings"
sleep 1

#CONFIGS
echo "Setting CPU Cores/Threads"
export CPUS=`nproc`
echo "Setting Version Number"
export VER=v$1
echo "Setting Extra Version"
export EV=EXTRAVERSION=_FlareX_v$1
echo "Setting Defconfig"
export DEFCONFIG=flareX_defconfig
echo "Setting bzImage Location For FlareX kernel"
export BZIMAGE=arch/x86/boot/bzImage
echo "Enabling Graphite Optimizations"
export ENABLE_GRAPHITE=true
echo "Set KBUILD_BUILD_VERSION to zero at all times"
export KBUILD_BUILD_VERSION="0"
echo "Enviroment Setup Complete Now Moving To Compiling"

#Build
echo "Cleaning Out Compiled Files"
sleep 1
#make clean
wmctrl -r :ACTIVE: -N "Starting Build Process"
echo "Starting Build Process"
export USE_CCACHE=1
sleep 1
if [ -f .config ];
then
   echo ".config exists"
   echo "Continuing To Compiler"
   sleep 1
else
   echo ".config Does Not Exists"
   echo "Compiling From $DEFCONFIG"
   make $DEFCONFIG
   sleep 1
fi

wmctrl -r :ACTIVE: -N "Compiling FareX Kernel"
make $EV -j$CPUS

if [ -f $BZIMAGE ];
then
   echo "$BZIMAGE exists"
   echo "Compile Complete Continuing To Packing"
   sleep 1
else
   echo "$BZIMAGE Does Not Exists Please Check For Compile Errors"
   echo "Now exiting script"
   sleep 1
   exit 0
fi
clear
#make it a bit more beautiful :P
echo "script made by eoghan2t7 of xda"
printf "say thanks to him if this helped you :) \n\n"
echo "Current Date : $NOW"
echo "Applying Build Settings : done"
echo "Version Number = $VER"
echo "cleaning previous files : done"
echo "Starting Build Process  : done"
echo "Build complete"

#Kernel Packing
wmctrl -r :ACTIVE: -N "FlareX Kernel Packing"
echo "Starting Packing To Recovery Flashable Zip"
cd out/
echo "Removing Old Files"
rm -rf bzImage *.zip
sleep 1
echo "Copying bzImage"
mv ../arch/x86/boot/bzImage bzImage
sleep 1
echo "Compiling FlareX_"$VER".zip"
find . -type f -exec zip FlareX_"$VER".zip {} +
nowf=$(date +"%T")
cd ..
make clean
rm out/bzImage
printf "cleaned files"
printf "\n\nzip created\n"
end=`date +%s`
runtime=$((end-start))
echo "Completion Time :"
echo "$runtime sec\n"
